import {
  DownloadIcon,
  FolderOpenIcon,
  LoaderIcon,
  PackageIcon,
  RefreshCwIcon,
  XIcon,
} from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { urlOfArtifact } from "@/core/artifacts/utils";
import { useFolderPicker } from "@/core/dreamy/hooks/use-folder-picker";
import {
  useClearMountedFolder,
  useMountedFolder,
  useSaveMountedFolder,
} from "@/core/dreamy/hooks/use-mounted-folder";
import { useMountedFolderFiles } from "@/core/dreamy/hooks/use-mounted-folder-files";
import { useI18n } from "@/core/i18n/hooks";
import { installSkill } from "@/core/skills/api";
import {
  getFileExtensionDisplayName,
  getFileIcon,
  getFileName,
} from "@/core/utils/files";
import { cn } from "@/lib/utils";

import { useArtifacts } from "./context";

export function ArtifactFileList({
  className,
  files,
  threadId,
}: {
  className?: string;
  files: string[];
  threadId: string;
}) {
  const { t } = useI18n();
  const { select: selectArtifact, setOpen } = useArtifacts();
  const [installingFile, setInstallingFile] = useState<string | null>(null);
  const { data: mountedFolder } = useMountedFolder(threadId);
  const saveMountedFolder = useSaveMountedFolder(threadId);
  const clearMountedFolder = useClearMountedFolder(threadId);
  const { data: mountedFolderFiles } = useMountedFolderFiles(threadId, Boolean(mountedFolder));
  const { pickFolder, isPicking } = useFolderPicker();

  const { mountedFiles, createdFiles } = useMemo(() => {
    const mounted: string[] = [];
    const created: string[] = [];
    for (const file of files) {
      if (file.startsWith("/mnt/user-data/mounted/")) {
        mounted.push(file);
      } else {
        created.push(file);
      }
    }
    // Also include mounted files discovered from mounted-folder API
    // (e.g. /mnt/user-data/mounted/.docs/* generated by /analyse).
    const mountedFromApi = (mountedFolderFiles?.files ?? [])
      .filter((f) => !f.is_dir)
      .map((f) => f.virtual_path);
    for (const file of mountedFromApi) {
      if (!mounted.includes(file)) {
        mounted.push(file);
      }
    }
    return { mountedFiles: mounted, createdFiles: created };
  }, [files, mountedFolderFiles]);
  const hasDocsFolder = useMemo(
    () => (mountedFolderFiles?.files ?? []).some((f) => f.is_dir && f.virtual_path === "/mnt/user-data/mounted/.docs"),
    [mountedFolderFiles],
  );

  const handleClick = useCallback(
    (filepath: string) => {
      selectArtifact(filepath);
      setOpen(true);
    },
    [selectArtifact, setOpen],
  );

  const handleInstallSkill = useCallback(
    async (e: React.MouseEvent, filepath: string) => {
      e.stopPropagation();
      e.preventDefault();

      if (installingFile) return;

      setInstallingFile(filepath);
      try {
        const result = await installSkill({
          thread_id: threadId,
          path: filepath,
        });
        if (result.success) {
          toast.success(result.message);
        } else {
          toast.error(result.message || "Failed to install skill");
        }
      } catch (error) {
        console.error("Failed to install skill:", error);
        toast.error("Failed to install skill");
      } finally {
        setInstallingFile(null);
      }
    },
    [threadId, installingFile],
  );

  const handleChangeMountedFolder = useCallback(async () => {
    try {
      const path = await pickFolder();
      if (path === null) return;
      const saved = await saveMountedFolder.mutateAsync(path);
      toast.success(`${t.chatUI.mountFolder.mounted}: ${saved}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to change mounted folder";
      toast.error(message);
    }
  }, [pickFolder, saveMountedFolder, t]);

  const handleUnmountMountedFolder = useCallback(async () => {
    try {
      await clearMountedFolder.mutateAsync();
      toast.success(t.chatUI.mountFolder.unmounted);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to unmount folder";
      toast.error(message);
    }
  }, [clearMountedFolder, t]);

  const mountedFolderActionDisabled =
    isPicking || saveMountedFolder.isPending || clearMountedFolder.isPending;

  const renderRow = useCallback(
    (file: string, source: "created" | "mounted") => {
      const metadata = source === "mounted"
        ? `${getFileExtensionDisplayName(file)} file • ${mountedFolder ?? "/mnt/user-data/mounted"}`
        : `${getFileExtensionDisplayName(file)} file • /mnt/user-data/outputs`;

      return (
        <li
          key={file}
          className="hover:bg-muted/50 grid cursor-pointer grid-cols-[minmax(0,1fr)_auto] items-center gap-2 rounded-md px-2 py-1.5"
          onClick={() => handleClick(file)}
        >
          <div className="flex min-w-0 items-center gap-2">
            <span className="text-muted-foreground shrink-0">
              {getFileIcon(file, "size-4")}
            </span>
            <div className="min-w-0">
              <p className="truncate text-sm font-medium">{getFileName(file)}</p>
              <p className="text-muted-foreground truncate text-xs">{metadata}</p>
            </div>
          </div>
          <div className="flex items-center gap-1" onClick={(e) => e.stopPropagation()}>
            {file.endsWith(".skill") && (
              <Button
                variant="ghost"
                size="icon-sm"
                disabled={installingFile === file}
                onClick={(e) => void handleInstallSkill(e, file)}
                title={t.common.install}
              >
                {installingFile === file ? (
                  <LoaderIcon className="size-4 animate-spin" />
                ) : (
                  <PackageIcon className="size-4" />
                )}
              </Button>
            )}
            <a
              href={urlOfArtifact({
                filepath: file,
                threadId,
                download: true,
              })}
              target="_blank"
            >
              <Button variant="ghost" size="icon-sm" title={t.common.download}>
                <DownloadIcon className="size-4" />
              </Button>
            </a>
          </div>
        </li>
      );
    },
    [handleClick, handleInstallSkill, installingFile, mountedFolder, t, threadId],
  );

  return (
    <div className={cn("flex w-full flex-col gap-4 overflow-y-auto", className)}>
      {createdFiles.length > 0 && (
        <section className="space-y-2">
          <div className="text-muted-foreground flex items-center gap-1.5 px-1 text-xs">
            <FolderOpenIcon className="size-3.5" />
            <span className="font-medium uppercase tracking-wide">Created Files</span>
            <span className="font-mono">/mnt/user-data/outputs</span>
          </div>
          <ul className="divide-border border-border divide-y rounded-md border">
            {createdFiles.map((file) => renderRow(file, "created"))}
          </ul>
        </section>
      )}

      {mountedFolder && (
        <section className="space-y-2">
          <div className="text-muted-foreground space-y-1 px-1 text-xs">
            <div className="flex items-center justify-between gap-3">
              <div className="flex min-w-0 items-center gap-1.5">
                <FolderOpenIcon className="size-3.5 shrink-0" />
                <span className="font-medium uppercase tracking-wide">Mounted Files</span>
              </div>
              <div className="flex shrink-0 items-center gap-1">
                <Button
                  variant="ghost"
                  size="sm"
                  disabled={mountedFolderActionDisabled}
                  onClick={() => void handleChangeMountedFolder()}
                >
                  <RefreshCwIcon className={cn("size-3.5", isPicking && "animate-spin")} />
                  {t.chatUI.mountFolder.change}
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  className="text-destructive hover:text-destructive"
                  disabled={mountedFolderActionDisabled}
                  onClick={() => void handleUnmountMountedFolder()}
                >
                  <XIcon className="size-3.5" />
                  {t.chatUI.mountFolder.unmount}
                </Button>
              </div>
            </div>
            <div className="font-mono text-[11px] break-all">{mountedFolder}</div>
            {hasDocsFolder && (
              <div className="font-mono text-[11px]">
                Detected folder: <span className="text-foreground">/mnt/user-data/mounted/.docs</span>
              </div>
            )}
          </div>
          {mountedFiles.length > 0 ? (
            <ul className="divide-border border-border divide-y rounded-md border">
              {mountedFiles.map((file) => renderRow(file, "mounted"))}
            </ul>
          ) : (
            <div className="text-muted-foreground rounded-md border px-3 py-2 text-xs">
              No files found in mounted folder.
            </div>
          )}
        </section>
      )}
    </div>
  );
}
