import json
import time
from pathlib import Path
from types import SimpleNamespace

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from src.config.paths import Paths
from src.gateway.routers import dreamy


class _ModelSuccess:
    def invoke(self, _messages):
        return SimpleNamespace(content="# Deep Repo Overview\n\nGenerated by model.")


class _ModelFailure:
    def invoke(self, _messages):
        raise RuntimeError("model boom")


@pytest.fixture()
def client(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    paths = Paths(tmp_path)
    monkeypatch.setattr(dreamy, "get_paths", lambda: paths)
    dreamy._REPO_OVERVIEW_JOBS.clear()
    dreamy._REPO_OVERVIEW_JOB_BY_THREAD.clear()
    dreamy._REPO_OVERVIEW_TASKS.clear()

    app = FastAPI()
    app.include_router(dreamy.router)
    with TestClient(app) as test_client:
        yield test_client, paths

    dreamy._REPO_OVERVIEW_JOBS.clear()
    dreamy._REPO_OVERVIEW_JOB_BY_THREAD.clear()
    dreamy._REPO_OVERVIEW_TASKS.clear()


def _mount_thread(test_client: TestClient, thread_id: str, mounted_dir: Path) -> None:
    mounted_dir.mkdir(parents=True, exist_ok=True)
    response = test_client.put(
        f"/api/threads/{thread_id}/dreamy/mount-folder",
        json={"path": str(mounted_dir.resolve())},
    )
    assert response.status_code == 200


def _wait_for_terminal_status(test_client: TestClient, thread_id: str, job_id: str) -> dict:
    deadline = time.time() + 8
    while time.time() < deadline:
        status_res = test_client.get(f"/api/threads/{thread_id}/analyse/repo-overview-refresh/{job_id}")
        assert status_res.status_code == 200
        payload = status_res.json()
        if payload.get("status") in {"succeeded", "failed"}:
            return payload
        time.sleep(0.1)
    raise AssertionError("refresh job did not reach terminal status in time")


def test_analyse_enqueues_durable_refresh_and_overwrites_repo_overview(
    client: tuple[TestClient, Paths], tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    test_client, paths = client
    thread_id = "thread_refresh_success"
    mounted_dir = tmp_path / "mounted-success"
    (mounted_dir / "app").mkdir(parents=True, exist_ok=True)
    (mounted_dir / "app" / "main.py").write_text("print('hello')\n", encoding="utf-8")
    _mount_thread(test_client, thread_id, mounted_dir)

    monkeypatch.setattr(dreamy, "create_chat_model", lambda **kwargs: _ModelSuccess())
    # Stage routing was removed in favor of the single-model invariant —
    # dreamy now calls ``resolve_model_name`` directly. Patch it here so the
    # test gets a deterministic "fake-model" without touching real app_config.
    monkeypatch.setattr(dreamy, "resolve_model_name", lambda _requested=None: "fake-model")
    monkeypatch.setattr(dreamy, "get_app_config", lambda: SimpleNamespace(models=[SimpleNamespace(name="fake-model")]))

    analyse_res = test_client.post(f"/api/threads/{thread_id}/analyse")
    assert analyse_res.status_code == 200
    analyse_payload = analyse_res.json()
    assert analyse_payload["repo_overview_refresh_job_id"]
    assert analyse_payload["repo_overview_refresh_status"] in {"queued", "running"}
    assert analyse_payload["repo_overview_refresh_queued_at"]

    job_id = analyse_payload["repo_overview_refresh_job_id"]
    status_payload = _wait_for_terminal_status(test_client, thread_id, job_id)
    assert status_payload["status"] == "succeeded"
    assert status_payload["attempt_count"] >= 1

    analyse_root = paths.sandbox_work_dir(thread_id) / ".analyse"
    assert (analyse_root / "repo_overview.md").exists()
    assert (analyse_root / "repo_overview.previous.md").exists()
    assert "Deep Repo Overview" in (analyse_root / "repo_overview.md").read_text(encoding="utf-8")

    store = json.loads((paths.sandbox_user_data_dir(thread_id) / "repo_overview_refresh_jobs.json").read_text(encoding="utf-8"))
    assert store["jobs"][-1]["job_id"] == job_id
    assert store["jobs"][-1]["status"] == "succeeded"


def test_refresh_retries_and_persists_failed_status(
    client: tuple[TestClient, Paths], tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    test_client, paths = client
    thread_id = "thread_refresh_failure"
    mounted_dir = tmp_path / "mounted-failure"
    (mounted_dir / "src").mkdir(parents=True, exist_ok=True)
    (mounted_dir / "src" / "app.py").write_text("print('x')\n", encoding="utf-8")
    _mount_thread(test_client, thread_id, mounted_dir)

    monkeypatch.setattr(dreamy, "create_chat_model", lambda **kwargs: _ModelFailure())
    monkeypatch.setattr(dreamy, "resolve_model_name", lambda _requested=None: "fake-model")
    monkeypatch.setattr(dreamy, "get_app_config", lambda: SimpleNamespace(models=[SimpleNamespace(name="fake-model")]))

    analyse_res = test_client.post(f"/api/threads/{thread_id}/analyse")
    assert analyse_res.status_code == 200
    job_id = analyse_res.json()["repo_overview_refresh_job_id"]
    status_payload = _wait_for_terminal_status(test_client, thread_id, job_id)
    assert status_payload["status"] == "failed"
    assert status_payload["attempt_count"] == dreamy._REPO_OVERVIEW_REFRESH_MAX_ATTEMPTS
    assert "failed after retries" in (status_payload.get("error") or "").lower()

    store = json.loads((paths.sandbox_user_data_dir(thread_id) / "repo_overview_refresh_jobs.json").read_text(encoding="utf-8"))
    assert store["jobs"][-1]["status"] == "failed"
    assert store["jobs"][-1]["attempt_count"] == dreamy._REPO_OVERVIEW_REFRESH_MAX_ATTEMPTS


def test_publishdocs_blocks_stale_refresh_unless_forced(client: tuple[TestClient, Paths], tmp_path: Path):
    test_client, paths = client
    thread_id = "thread_publish_guard"
    mounted_dir = tmp_path / "mounted-publish"
    mounted_dir.mkdir(parents=True, exist_ok=True)
    _mount_thread(test_client, thread_id, mounted_dir)

    docs_root = paths.sandbox_work_dir(thread_id) / ".docs"
    analyse_root = paths.sandbox_work_dir(thread_id) / ".analyse"
    docs_root.mkdir(parents=True, exist_ok=True)
    analyse_root.mkdir(parents=True, exist_ok=True)
    (docs_root / "src").mkdir(parents=True, exist_ok=True)
    (docs_root / "src" / "app.py.md").write_text("# src/app.py\n", encoding="utf-8")
    (analyse_root / "index.md").write_text("# index\n", encoding="utf-8")
    (analyse_root / "repo_overview.md").write_text("# deterministic\n", encoding="utf-8")

    stale_job = dreamy._RepoOverviewRefreshJob(
        job_id="job-stale",
        thread_id=thread_id,
        status="failed",
        created_at="2026-01-01T00:00:00+00:00",
        finished_at="2026-01-01T00:00:01+00:00",
        error="failed for test",
        trigger="analyse",
    )
    dreamy._persist_job(stale_job)

    blocked = test_client.post(f"/api/threads/{thread_id}/publishdocs")
    assert blocked.status_code == 409
    detail = blocked.json().get("detail") or {}
    assert detail.get("job_id") == "job-stale"
    assert detail.get("status") == "failed"

    forced = test_client.post(f"/api/threads/{thread_id}/publishdocs?force=true")
    assert forced.status_code == 200
    assert forced.json()["copied_files"] >= 1
