"""Configuration for planner middleware."""

from pydantic import BaseModel, Field


class PlannerConfig(BaseModel):
    """Planner behavior configuration."""

    enabled: bool = Field(
        default=True,
        description="Enable planner stage in Plan mode.",
    )
    max_plan_steps: int = Field(
        default=8,
        ge=1,
        le=50,
        description="Maximum number of todo items generated by planner.",
    )
    max_clarifications: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Maximum number of clarification questions the planner may generate.",
    )
    # Opt-in: when true and the planner's domain is "research", todos with no
    # depends_on edges are surfaced to the agent prompt as candidates for
    # parallel `task` subagent dispatch. The lead agent issues one `task` call
    # per independent todo (capped by SubagentLimitMiddleware) and synthesizes
    # results in a final cycle. Default off — enabling changes the trajectory
    # shape and is materially faster for fan-out research workloads. Can also
    # be toggled per-thread via runtime config: `is_research_fanout=True`.
    research_fanout: bool = Field(
        default=False,
        description="Enable automatic subagent fan-out for independent research todos.",
    )
    research_fanout_min_todos: int = Field(
        default=2,
        ge=2,
        le=20,
        description="Minimum number of independent todos required before fan-out is suggested.",
    )


_planner_config: PlannerConfig = PlannerConfig()


def get_planner_config() -> PlannerConfig:
    """Get current planner configuration."""
    return _planner_config


def set_planner_config(config: PlannerConfig) -> None:
    """Set planner configuration."""
    global _planner_config
    _planner_config = config


def load_planner_config_from_dict(config_dict: dict) -> None:
    """Load planner configuration from dictionary."""
    global _planner_config
    _planner_config = PlannerConfig(**config_dict)
